### PR TITLE
add Resources.js and Resources.css files

### PR DESCRIPTION
**Pull request by elenademi**
## Description

In this PR, I created a new page called "resources" and added 2 files to it: Resources.js and Resources.css. Mock data is rendered on the page. I made changes to App.js, adding a Route to the new page and importing Resources.js. I made changes to the Landing Page, adding a link to the Resources page to the Resources heading.

## Testing Steps / QA Criteria

Check if the mock data is rendered and correctly sorted by topic and subtopic. 

© 2022 GitHub, Inc.
Terms
Privacy
Security
Status

### CODE REVIEW

**Review by Alzhan-B — APPROVED** [review]
Looks good.

**Comment by elenademi** [comment]
Thank you!
When I do the steps you suggested with installing Prettier, does it have
any settings that need to be changed to match everyone else's settings, or
are they standard?

**Comment by nikkigraybeal** [comment]
@elenademi I put more detailed instructions in your center login PR. I think the VS Code extension will pick up the .prettierrc file and that is where it gets the formatting rules that we are all using. As long as we all use the same formatting rules in the prettierrc file, our formatting should match. I think Prettier comes with some standard formatting defaults but we use the prettierrc file to adjust those defaults.

**Comment by elenademi** [comment]
Hi Nikki,
Thank you for the instructions!
I believe Prettier is working now. I ran it on each file, then committed
the changes and pushed them. Not sure if I had to merge main first, but
decided not to, because the Resources page does not exist in the main
branch yet. So, I figured it will disappear if I pull from main. Is that
right, or  should I have done it differently?
Thank so much for helping,
Elena

**Comment by nikkigraybeal** [comment]
@elenademi you actually do need to merge main into this branch and then commit and push again. A merge will combine the code in 2 separate branches so you won't lose your work! 

The only tricky part for merging is when there is conflicting code on the same lines. It happens like this: you branch from main to make a new branch, then make changes to the code on that branch. In the meantime, someone else creates another branch, makes changes and those changes get merged to main. 

Now, if you both happened to make changes to the same lines of code and you try to merge main into your branch, git doesn't know whose code to keep. So, we get a conflict that we have to resolve. We either keep the code coming from main or the code from our branch or a combination of the two. And knowing which to do can be difficult! 

Let me know if you want to hop on a huddle and work through it together tomorrow before our meeting.

**Comment by elenademi** [comment]
That would be great, thank you!  So, if the files I created don't exist in
the main branch, they won't disappear after I pull from it?

**Review by nikkigraybeal — APPROVED** [review]
Great job, Elena! It's ready.

**Pull request merged**
