### PR TITLE
Pract-72/updated styling for LoginPage

### PR DESCRIPTION
**Pull request by koral14**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

Update styling for Login page. Added responsiveness to up to 320 px. 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: Updated UI     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

image

### After

image

image

image

## Testing Steps / QA Criteria

© 2022 GitHub, Inc.
Terms
Privacy
Security
Status

### CODE REVIEW

**Review by nikkigraybeal — APPROVED** [review]
This looks awesome, Olga!! Thank you!

**Review by madebymiguel — CHANGES_REQUESTED** [review]
Overall it looks good. A couples of points here:

- Hard to tell that the create one "here" link is a link. Make it stick out more
- Not really important but you could make the link be a one liner _Don't have an account? Sign Up_ and just increase the width to have it fit. 
- A bit too much bottom padding/margin. Try to match the top padding/margin

**Review by madebymiguel — APPROVED** [review]
LGTM!

**Review by nikkigraybeal — APPROVED** [review]
Awesome work - looks great!

**Pull request merged**
