### PR TITLE
center login form on the page

### PR DESCRIPTION
**Pull request by elenademi**
Description

A CSS file has been created in order to center the login form on the login page. A button redirecting the user to the registration page has been added under the submit button.

### CODE REVIEW

**Review by Alzhan-B — APPROVED** [review]
Looks good

**Review by nikkigraybeal — CHANGES_REQUESTED** [review]
The login page looks great, Elena! 

Just a very small nitpick on spacing/empty lines in your code. We generally add empty lines between sections and functions in our components, so add a line between the imports and the function definition in the LoginPage.js file and a line before and after the submit handler.

Also, in CSS files, we generally add a line between selectors but no extra lines inside the rule set. And there should be a space between the selector and the `{` too. So it should look something like this:

```
.container {
    margin: 5px;
    width: 100%;
}

button {
    margin: 5px;
    width: 40px;
}
```

**Comment by elenademi** [comment]
Thank you!
I was trying to install Prettier - is that what you use for making the code
look uniform? I understood from Alejandro's instructions that you should do
git pull and git i. I did that, but at different times, and it doesn't look
like it got installed.

**Comment by nikkigraybeal** [comment]
> Thank you! I was trying to install Prettier - is that what you use for making the code look uniform? I understood from Alejandro's instructions that you should do git pull and git i. I did that, but at different times, and it doesn't look like it got installed.

@elenademi You need to create a `.prettierrc` file and a `.prettierignore` file  at the root the frontend file system and also do `npm i`. 

Then either install the prettier extension in VS Code or run `npm prettier-watch` in a terminal from your root frontend folder (you can have separate terminals running this and then a different one running your server using `npm run start`). i think as long as the watcher is running it will prettify your code whenever you make changes. 

I think one more way to get prettier to work is to run `npm format` in the terminal from the root folder of the frontend. 

just FYI: both `format` and `prettier-watch` are scripts that are defined in package.json. That's where we get the `start` script from as well.

**Review by nikkigraybeal — APPROVED** [review]

**Pull request merged**
